language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
services: 
- postgresql
before_script:
 - psql -c 'CREATE DATABASE mentors;' -U jordan
script: 
  - npm test
after_success: 
  - npm run coverage